language: cpp
before_script:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install g++-7 -y
- cd /usr/bin
- sudo rm g++
- sudo ln g++-7 g++
- sudo apt purge cmake
- sudo apt purge --auto-remove cmake
- version=3.12
- build=2
- mkdir ~/temp
- cd ~/temp
- wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
- tar -xzvf cmake-$version.$build.tar.gz
- cd cmake-$version.$build/
- ./bootstrap
- make -j4
- sudo make install
- sudo apt-get install libgtest-dev -y
- cd /usr/src/gtest
- sudo env "PATH=$PATH" cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd "${TRAVIS_BUILD_DIR}"
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
- provider: script
  skip_cleanup: true
  script:
  - curl -T bulkmt-0.1.$TRAVIS_BUILD_NUMBER-Linux.deb -uolegworld:$BINTRAY_API_KEY "https://api.bintray.com/content/olegworld/Otus_Homework/bulkmt/$TRAVIS_BUILD_NUMBER/bulkmt-0.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"